import { RouteInfo } from './sidebar.metadata';
export const ROUTES: RouteInfo[] = [
  {
    path: '',
    title: 'MENUITEMS.MAIN.TEXT',
    iconType: '',
    icon: '',
    class: '',
    groupTitle: true,
    badge: '',
    badgeClass: '',
    role: ['All'],
    submenu: [],
  },

  // Admin Modules
  {
    path: '',
    title: 'MENUITEMS.DASHBOARD.TEXT',
    iconType: 'material-icons-outlined',
    icon: 'space_dashboard',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin'],
    submenu: [
      {
        path: '/admin/dashboard/main',
        title: 'MENUITEMS.DASHBOARD.LIST.DASHBOARD1',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/admin/dashboard/dashboard2',
        title: 'MENUITEMS.DASHBOARD.LIST.DASHBOARD2',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/admin/dashboard/doctor-dashboard',
        title: 'MENUITEMS.DASHBOARD.LIST.DOCTOR-DASHBOARD',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/admin/dashboard/patient-dashboard',
        title: 'MENUITEMS.DASHBOARD.LIST.PATIENT-DASHBOARD',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'MENUITEMS.APPOINTMENTS.TEXT',
    iconType: 'material-icons-outlined',
    icon: 'assignment',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin'],
    submenu: [
      {
        path: '/admin/appointment/viewAppointment',
        title: 'MENUITEMS.APPOINTMENTS.LIST.VIEW-APPOINTMENT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/admin/appointment/bookAppointment',
        title: 'MENUITEMS.APPOINTMENTS.LIST.BOOK-APPOINTMENT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/admin/appointment/edit-ppointment',
        title: 'MENUITEMS.APPOINTMENTS.LIST.EDIT-APPOINTMENT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
    ],
  },

  {
    path: '',
    title: 'Master',
    iconType: 'material-icons-outlined',
    icon: 'people_alt',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin'],
    submenu: [
      {
        path: '/admin/section/section-list',
        title: 'MENUITEMS.SECTION.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/admin/departments/department-list',
        title: 'MENUITEMS.DEPARTMENTS.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
            path: '/admin/subdepartments/subdepartments-list',
            title: 'MENUITEMS.SUBDEPARTMENT.TEXT',
            iconType: '',
            icon: '',
            class: 'ml-menu',
            groupTitle: false,
            badge: '',
            badgeClass: '',
            role: [''],
            submenu: [],
      },

      {
        path: '/admin/bank/bank-list',
        title: 'MENUITEMS.BANK.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Admin'],
        submenu: []
      },
      {
        path: '/admin/designation/designation-list',
        title: 'MENUITEMS.DESIGNATION.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Admin'],
        submenu: [],
      },
      {
        path: 'admin/occupation/occupation-list',
        title: 'Occupation',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Admin'],
        submenu: []
      },
      {
        path: '/admin/patientscategory/patientscategory-list',
        title: 'MENUITEMS.PATIENTS-CATEGORY.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Admin'],
        submenu: []
      },
      {
        path: '/admin/patientcompany/patientcompany-list',
        title: 'MENUITEMS.PATIENT-COMPANY.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Admin'],
        submenu: []
      },
      {
        path: '/admin/ratetype/ratetype-list',
        title: 'MENUITEMS.RATE-TYPE.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Admin'],
        submenu: []
      },
      {
        path: '/admin/role/role-list',
        title: 'MENUITEMS.ROLE.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Admin'],
        submenu: []
      },
      {
        path: '/admin/specialization/specialization-list',
        title: 'MENUITEMS.SPECIALIZATION.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Admin'],
        submenu: []
      },
      {
        path: '/admin/servicegroup/servicegroup-list',
        title: 'MENUITEMS.SERVICEGROUP.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Admin'],
        submenu: []
      },
      {
        path: '/admin/services/services-list',
        title: 'MENUITEMS.SERVICES.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Admin'],
        submenu: []
      },
      {
        path: '/admin/userdepartment/userdepartment-list',
        title: 'MENUITEMS.USERDEPARTMENT.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Admin'],
        submenu: []
      },
      {
        path: '/admin/userrole/userrole-list',
        title: 'MENUITEMS.USERROLE.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Admin'],
        submenu: []
      },
      {
        path: 'admin/hospital/hospital-list',
        title: 'MENUITEMS.HOSPITALS.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Admin'],
        submenu: []
      },
      {
        path: 'admin/master/pharmacy-list',
        title: 'MENUITEMS.PHARMACY.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Admin'],
        submenu: []
      },
      {
        path: 'admin/route/route-list',
        title: 'MENUITEMS.ROUTE.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Admin'],
        submenu: []
      },
      {
        path: 'admin/consume/consume-list',
        title: 'MENUITEMS.CONSUME.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Admin'],
        submenu: []
      },
      {
        path: 'admin/doses/doses-list',
        title: 'MENUITEMS.DOSES.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Admin'],
        submenu: []
      },
      {
        path: 'admin/quantity/quantity-list',
        title: 'MENUITEMS.QUANTITY.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Admin'],
        submenu: []
      },
      {
        path: '/admin/master/unit-list',
        title: 'MENUITEMS.UNIT.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/admin/master/pathology-test-list',
        title: 'MENUITEMS.PATHOLOGYTEST.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/admin/master/x-ray-list',
        title: 'MENUITEMS.X-RAY.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/admin/master/sonography-list',
        title: 'MENUITEMS.SONOGRAPHY.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/admin/master/package-master-list',
        title: 'MENUITEMS.PACKAGEMASTER.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      }
      ,
      {
        path: '/admin/master/template-list',
        title: 'MENUITEMS.TEMPLATE.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/admin/master/anesthesia-type-list',
        title: 'MENUITEMS.ANESTHESIA.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/admin/master/operation-type-list',
        title: 'MENUITEMS.OPERATIONTYPE.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/admin/master/note-template-list',
        title: 'MENUITEMS.NOTE-TEMPLATE.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
       {
        path: '/admin/master/gynecology-notes-template',
        title: 'MENUITEMS.Gynecology-TEMPLATE.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/admin/master/floor-list',
        title: 'MENUITEMS.FLOOR.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/admin/master/billing-class-list',
        title: 'MENUITEMS.BILLING_CLASS.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/admin/master/room-type-list',
        title: 'MENUITEMS.ROOM_TYPE.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/admin/master/room-list',
        title: 'MENUITEMS.ROOM.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      } ,
      {
        path: '/admin/master/bed-list',
        title: 'MENUITEMS.BED.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      }
    ],
  },

  {
    path: '',
    title: 'MENUITEMS.DOCTORS.TEXT',
    iconType: 'material-icons-outlined',
    icon: 'supervised_user_circle',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin'],
    submenu: [
      {
        path: '/admin/doctors/allDoctors',
        title: 'MENUITEMS.DOCTORS.LIST.ALL-DOCTOR',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      // {
      //   path: '/admin/doctors/add-doctor',
      //   title: 'MENUITEMS.DOCTORS.LIST.ADD-DOCTOR',
      //   iconType: '',
      //   icon: '',
      //   class: 'ml-menu',
      //   groupTitle: false,
      //   badge: '',
      //   badgeClass: '',
      //   role: [''],
      //   submenu: [],
      // },
      // {
      //   path: '/admin/doctors/edit-doctor',
      //   title: 'MENUITEMS.DOCTORS.LIST.EDIT-DOCTOR',
      //   iconType: '',
      //   icon: '',
      //   class: 'ml-menu',
      //   groupTitle: false,
      //   badge: '',
      //   badgeClass: '',
      //   role: [''],
      //   submenu: [],
      // },
      {
        path: '/admin/doctors/doctor-profile',
        title: 'MENUITEMS.DOCTORS.LIST.PROFILE',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'MENUITEMS.EMPLOYEES.TEXT',
    iconType: 'material-icons-outlined',
    icon: 'people_alt',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin'],
    submenu: [
      {
        path: '/admin/employees/all-employees',
        title: 'MENUITEMS.EMPLOYEES.LIST.ALL-EMPLOYEE',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      // {
      //   path: '/admin/employees/add-employee',
      //   title: 'MENUITEMS.EMPLOYEES.LIST.ADD-EMPLOYEE',
      //   iconType: '',
      //   icon: '',
      //   class: 'ml-menu',
      //   groupTitle: false,
      //   badge: '',
      //   badgeClass: '',
      //   role: [''],
      //   submenu: [],
      // },
      // {
      //   path: '/admin/employees/edit-employee',
      //   title: 'MENUITEMS.EMPLOYEES.LIST.EDIT-EMPLOYEE',
      //   iconType: '',
      //   icon: '',
      //   class: 'ml-menu',
      //   groupTitle: false,
      //   badge: '',
      //   badgeClass: '',
      //   role: [''],
      //   submenu: [],
      // },
      {
        path: '/admin/employees/employee-profile',
        title: 'MENUITEMS.EMPLOYEES.LIST.PROFILE',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'MENUITEMS.PATIENTS.TEXT',
    iconType: 'material-icons-outlined',
    icon: 'face',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin'],
    submenu: [
      {
        path: '/admin/patients/all-patients',
        title: 'MENUITEMS.PATIENTS.LIST.ALL-PATIENT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      // {
      //   path: '/admin/patients/add-patient',
      //   title: 'MENUITEMS.PATIENTS.LIST.ADD-PATIENT',
      //   iconType: '',
      //   icon: '',
      //   class: 'ml-menu',
      //   groupTitle: false,
      //   badge: '',
      //   badgeClass: '',
      //   role: [''],
      //   submenu: [],
      // },
      // {
      //   path: '/admin/patients/edit-patient',
      //   title: 'MENUITEMS.PATIENTS.LIST.EDIT-PATIENT',
      //   iconType: '',
      //   icon: '',
      //   class: 'ml-menu',
      //   groupTitle: false,
      //   badge: '',
      //   badgeClass: '',
      //   role: [''],
      //   submenu: [],
      // },
      // {
      //   path: '/admin/patients/patient-profile',
      //   title: 'MENUITEMS.PATIENTS.LIST.PROFILE',
      //   iconType: '',
      //   icon: '',
      //   class: 'ml-menu',
      //   groupTitle: false,
      //   badge: '',
      //   badgeClass: '',
      //   role: [''],
      //   submenu: [],
      // },
    ],
  },
  {
    path: '',
    title: 'MENUITEMS.ROOMS.TEXT',
    iconType: 'material-icons-outlined',
    icon: 'hotel',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin'],
    submenu: [
      {
        path: '/admin/room/all-rooms',
        title: 'MENUITEMS.ROOMS.LIST.ALLOTED-ROOMS',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/admin/room/add-allotment',
        title: 'MENUITEMS.ROOMS.LIST.NEW-ALLOTMENT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/admin/room/edit-allotment',
        title: 'MENUITEMS.ROOMS.LIST.EDIT-ALLOTMENT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'MENUITEMS.BILLING.TEXT',
    iconType: 'material-icons-outlined',
    icon: 'monetization_on',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin'],
    submenu: [
      {
        path: '/admin/billing/bill-list',
        title: 'MENUITEMS.BILLING.LIST.BILL-LIST',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/admin/billing/add-bill',
        title: 'MENUITEMS.BILLING.LIST.ADD-BILL',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/admin/billing/invoice',
        title: 'MENUITEMS.BILLING.LIST.INVOICE',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'MENUITEMS.RECORDS.TEXT',
    iconType: 'material-icons-outlined',
    icon: 'list_alt',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin'],
    submenu: [
      {
        path: '/admin/records/birth',
        title: 'MENUITEMS.RECORDS.LIST.BIRTH-RECORDS',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/admin/records/death',
        title: 'MENUITEMS.RECORDS.LIST.DEATH-RECORDS',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'MENUITEMS.AMBULANCE.TEXT',
    iconType: 'material-icons-outlined',
    icon: 'airport_shuttle',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin'],
    submenu: [
      {
        path: '/admin/ambulance/call-list',
        title: 'MENUITEMS.AMBULANCE.LIST.AMBULANCE-CALL-LIST',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/admin/ambulance/list',
        title: 'MENUITEMS.AMBULANCE.LIST.AMBULANCE-LIST',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'MENUITEMS.PHARMACY.TEXT',
    iconType: 'material-icons-outlined',
    icon: 'local_pharmacy',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin'],
    submenu: [
      {
        path: '/admin/pharmacy/medicine-list',
        title: 'MENUITEMS.PHARMACY.LIST.MEDICINE-LIST',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/admin/pharmacy/add-medicine',
        title: 'MENUITEMS.PHARMACY.LIST.ADD-MEDICINE',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
    ],
  },

  {
    path: '',
    title: 'MENUITEMS.INVENTORY.TEXT',
    iconType: 'material-icons-outlined',
    icon: 'shopping_bag',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin'],
    submenu: [
      {
        path: '/admin/inventory/item-stock-list',
        title: 'MENUITEMS.INVENTORY.LIST.ITEM-STOCK-LIST',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/admin/inventory/issued-items',
        title: 'MENUITEMS.INVENTORY.LIST.ISSUED-ITEMS',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
    ],
  },


//RMO module

  // Doctor Modules
  {
    path: '/doctor/dashboard',
    title: 'MENUITEMS.DOCTOR.DASHBOARD',
    iconType: 'material-icons-outlined',
    icon: 'space_dashboard',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['RMO'],
    submenu: [],
  },
  {
    path: '',
    title: 'OPD',
    iconType: 'material-icons-outlined',
    icon: 'shopping_bag',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['RMO'],
    submenu: [
      {
        path: '/doctor/casualty-appointments',
        title: 'Waiting for Casualty',
        iconType: 'material-icons-outlined',
        icon: 'assignment',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['RMO'],
        submenu: [],
      }
    ]
    },
















  // Doctor Modules
  {
    path: '/doctor/dashboard',
    title: 'MENUITEMS.DOCTOR.DASHBOARD',
    iconType: 'material-icons-outlined',
    icon: 'space_dashboard',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Doctor'],
    submenu: [],
  },
  {
    path: '',
    title: 'OPD',
    iconType: 'material-icons-outlined',
    icon: 'shopping_bag',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Doctor'],
    submenu: [
      {
        path: '/doctor/casualty-appointments',
        title: 'Waiting for Casualty',
        iconType: 'material-icons-outlined',
        icon: 'assignment',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Doctor'],
        submenu: [],
      },
      {
        path: '/doctor/appointments',
        title: 'Waiting for Doctor',
        iconType: 'material-icons-outlined',
        icon: 'assignment',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Doctor'],
        submenu: [],
      },
      {
        path: '/doctor/completed-appointments',
        title: 'Completed Appointments',
        iconType: 'material-icons-outlined',
        icon: 'assignment',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Doctor'],
        submenu: [],
      },
      {
        path: '/doctor/special-cases',
        title: 'Special Cases',
        iconType: 'material-icons-outlined',
        icon: 'assignment',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Doctor'],
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'IPD',
    iconType: 'material-icons-outlined',
    icon: 'shopping_bag',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Doctor', 'Nurse'],
    submenu: [
      {
        path: '/doctor/initial-clinical-assessment-list',
        title: 'Recommended IPDs',
        iconType: 'material-icons-outlined',
        icon: 'assignment',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Doctor', 'Nurse'],
        submenu: [],
      },
      {
        path: '/doctor/emergency-clinical-assessment-list',
        title: 'Recommended Emergencies',
        iconType: 'material-icons-outlined',
        icon: 'assignment',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Doctor', 'Nurse'],
        submenu: [],
      },
      {
        path: '/nurse/bed-management',
        title: 'Admitted Patients',
        iconType: 'material-icons-outlined',
        icon: 'assignment',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Doctor', 'Nurse'],
        submenu: [],
      },
      {
        path: '/nurse/my-patients',
        title: 'My Patients',
        iconType: 'material-icons-outlined',
        icon: 'assignment',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Doctor'],
        submenu: [],
      },
      {
        path: '/doctor/ipd-completed-appointments',
        title: 'IPD Discharged',
        iconType: 'material-icons-outlined',
        icon: 'assignment',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Doctor', 'Nurse'],
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'OT',
    iconType: 'material-icons-outlined',
    icon: 'shopping_bag',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Doctor', 'Nurse'],
    submenu: [
      {
        path: '/doctor/ot-registration',
        title: 'Book OT',
        iconType: 'material-icons-outlined',
        icon: 'assignment',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Doctor', 'Nurse'],
        submenu: [],
      },
      {
        path: '/doctor/operations',
        title: 'Operations',
        iconType: 'material-icons-outlined',
        icon: 'assignment',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Doctor', 'Nurse'],
        submenu: [],
      },
    ],
  },
  {
    path: '/doctor/initial-clinical-assessment',
    title: 'Initial Assessment',
    iconType: 'material-icons-outlined',
    icon: 'notes',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Doctor'],
    submenu: [],
  },
  {
    path: '/doctor/emergency-clinical-assessment',
    title: 'Emergency Assessment',
    iconType: 'material-icons-outlined',
    icon: 'notes',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Doctor'],
    submenu: [],
  },
  {
    path: '/doctor/doctors',
    title: 'MENUITEMS.DOCTOR.DOCTORS',
    iconType: 'material-icons-outlined',
    icon: 'supervised_user_circle',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Doctor'],
    submenu: [],
  },
  {
    path: '/apps/chat',
    title: 'MENUITEMS.DOCTOR.CHAT',
    iconType: 'material-icons-outlined',
    icon: 'chat',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Doctor'],
    submenu: [],
  },
   // Accountant Modules
   {
    path: '/accountant/dashboard',
    title: 'MENUITEMS.PATIENT.DASHBOARD',
    iconType: 'material-icons-outlined',
    icon: 'space_dashboard',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Accountant'],
    submenu: [],
  },
    {
        path: '/accountant/registration',
        title: 'Waiting To Pay',
        iconType: 'material-icons-outlined',
        icon: 'assignment',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Accountant'],
        submenu: [],
      },
      {
        path: '/accountant/todays-payments',
        title: 'Payments',
        iconType: 'material-icons-outlined',
        icon: 'payment',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Accountant'],
        submenu: [],
      },
      {
        path: '/accountant/billing',
        title: 'Billing',
        iconType: 'material-icons-outlined',
        icon: 'receipt',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Accountant'],
        submenu: [],
      },

      {
        path: '/reception/appointments/cashbook',
        title: 'Cashbook',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
  
 
  // {
  //   path: '/accountant/past-billing',
  //   title: 'Past Billing',
  //   iconType: 'material-icons-outlined',
  //   icon: 'receipt',
  //   class: '',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   role: ['Accountant'],
  //   submenu: [],
  // },
  // reception Modules
  {
    path: '/reception/dashboard',
    title: 'MENUITEMS.PATIENT.DASHBOARD',
    iconType: 'material-icons-outlined',
    icon: 'space_dashboard',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Receptionist'],
    submenu: [],
  },
  {
    path: '',
    title: 'OPD',
    iconType: 'material-icons-outlined',
    icon: 'assignment',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Receptionist'],
    submenu: [

      {
        path: '/reception/appointments/oncallbooking',
        title: 'On Call Booking',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/reception/appointments/book',
        title: 'Registration',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/reception/appointments/today',
        title: 'Appointments',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },


  


      

      
      // {
      //   path: '/reception/appointments/upcoming',
      //   title: 'MENUITEMS.PATIENT.APPOINTMENTS.LIST.UPCOMING',
      //   iconType: '',
      //   icon: '',
      //   class: 'ml-menu',
      //   groupTitle: false,
      //   badge: '',
      //   badgeClass: '',
      //   role: [''],
      //   submenu: [],
      // },
      // {
      //   path: '/reception/appointments/past',
      //   title: 'MENUITEMS.PATIENT.APPOINTMENTS.LIST.PAST',
      //   iconType: '',
      //   icon: '',
      //   class: 'ml-menu',
      //   groupTitle: false,
      //   badge: '',
      //   badgeClass: '',
      //   role: [''],
      //   submenu: [],
      // },
    ],
  },
  {
    path: '/reception/appointments/recommended-operations',
    title: 'Recommended Operations',
    iconType: 'material-icons-outlined',
    icon: 'assignment',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Receptionist'],
    submenu: [],
  },
  {
    path: '/reception/appointments/recommended-admissions',
    title: 'Recommended Admits',
    iconType: 'material-icons-outlined',
    icon: 'assignment',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Receptionist'],
    submenu: [],
  },
  {
    path: '/reception/bed-management',
    title: 'Bed Statuses',
    iconType: 'material-icons-outlined',
    icon: 'bed',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Receptionist'],
    submenu: [],
  },
  {
    path: '/apps/chat',
    title: 'MENUITEMS.PATIENT.CHAT',
    iconType: 'material-icons-outlined',
    icon: 'chat',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Patient'],
    submenu: [],
  },
  {
    path: '/reception/settings',
    title: 'MENUITEMS.PATIENT.SETTINGS',
    iconType: 'material-icons-outlined',
    icon: 'settings',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Patient'],
    submenu: [],
  },

  // Common Modules
  {
    path: '',
    title: 'Apps',
    iconType: '',
    icon: '',
    class: '',
    groupTitle: true,
    badge: '',
    badgeClass: '',
    role: ['Admin', 'Doctor'],
    submenu: [],
  },
  {
    path: 'calendar',
    title: 'Calendar',
    iconType: 'material-icons-outlined',
    icon: 'event_note',
    class: '',
    groupTitle: false,
    badge: 'New',
    badgeClass: 'badge bg-blue sidebar-badge float-end',
    role: ['Admin', 'Doctor'],
    submenu: [],
  },
  {
    path: 'task',
    title: 'Task',
    iconType: 'material-icons-outlined',
    icon: 'fact_check',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin', 'Doctor'],
    submenu: [],
  },
  {
    path: 'contacts',
    title: 'Contacts',
    iconType: 'material-icons-outlined',
    icon: 'contacts',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin', 'Doctor'],
    submenu: [],
  },
  {
    path: '',
    title: 'Email',
    iconType: 'material-icons-outlined',
    icon: 'email',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin', 'Doctor'],
    submenu: [
      {
        path: '/email/inbox',
        title: 'Inbox',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/email/compose',
        title: 'Compose',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/email/read-mail',
        title: 'Read Email',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'More Apps',
    iconType: 'material-icons-outlined',
    icon: 'stars',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '4',
    badgeClass: 'badge bg-orange sidebar-badge float-end',
    role: ['Admin'],
    submenu: [
      {
        path: '/apps/chat',
        title: 'Chat',
        iconType: 'material-icons-outlined',
        icon: 'chat',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/apps/contact-grid',
        title: 'Contact Grid',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/apps/dragdrop',
        title: 'Drag & Drop',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/apps/support',
        title: 'Support',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'MENUITEMS.DASHBOARD.TEXT',
    iconType: 'material-icons-outlined',
    icon: 'space_dashboard',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Lab'],
    submenu: [
      {
        path: '/lab/dashboard',
        title: 'MENUITEMS.DASHBOARD.LIST.DASHBOARD1',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      } 
       ],
  },
  {
    path: '',
    title: 'MENUITEMS.REGISTRATIONS.TEXT',
    iconType: 'material-icons-outlined',
    icon: 'assignment',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Lab'],
    submenu: [
      {
        path: '/lab/registration-list',
        title: 'MENUITEMS.REGISTRATIONS.LIST.REGISTRATION',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },{
        path: '/lab/sample-collected-list',
        title: 'Sample Collected',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },{
        path: '/lab/registration-list-pending',
        title: 'Pending for Approval',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },{
        path: '/lab/registration-list-approve',
        title: 'Approved Reports',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },{
        path: '/lab/x-ray-registration-list',
        title: 'MENUITEMS.REGISTRATIONS.LIST.X-RAY_REGISTRATION',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },{
        path: '/lab/sonography-registration-list',
        title: 'MENUITEMS.REGISTRATIONS.LIST.SONOGRAPHY_REGISTRATION',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      }
    ],
  },
  //IPD Module
  {
    path: '/nurse/dashboard',
    title: 'MENUITEMS.PATIENT.DASHBOARD',
    iconType: 'material-icons-outlined',
    icon: 'space_dashboard',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Nurse'],
    submenu: [],
  },
  // {
  //   path: '',
  //   title: 'IPD',
  //   iconType: 'material-icons-outlined',
  //   icon: 'assignment',
  //   class: 'menu-toggle',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   role: ['Nurse'],
  //   submenu: [
  //     {
  //       path: '/nurse/appointments/book',
  //       title: 'Registration',
  //       iconType: '',
  //       icon: '',
  //       class: 'ml-menu',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       role: [''],
  //       submenu: [],
  //     },
  //     {
  //       path: '/nurse/appointments/today',
  //       title: 'MENUITEMS.PATIENT.APPOINTMENTS.LIST.TODAY',
  //       iconType: '',
  //       icon: '',
  //       class: 'ml-menu',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       role: [''],
  //       submenu: [],
  //     },
  //     {
  //       path: '/nurse/appointments/upcoming',
  //       title: 'MENUITEMS.PATIENT.APPOINTMENTS.LIST.UPCOMING',
  //       iconType: '',
  //       icon: '',
  //       class: 'ml-menu',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       role: [''],
  //       submenu: [],
  //     },
  //     {
  //       path: '/nurse/appointments/past',
  //       title: 'MENUITEMS.PATIENT.APPOINTMENTS.LIST.PAST',
  //       iconType: '',
  //       icon: '',
  //       class: 'ml-menu',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       role: [''],
  //       submenu: [],
  //     },
  //     {
  //       path: '/nurse/bed-management',
  //       title: 'MENUITEMS.BED-MANAGEMENT.TEXT',
  //       iconType: '',
  //       icon: '',
  //       class: 'ml-menu',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       role: [''],
  //       submenu: [],
  //     },
  //   ],
  // },
  // {
  //   path: '/nurse/prescriptions',
  //   title: 'MENUITEMS.PATIENT.PRESCRIPTIONS',
  //   iconType: 'material-icons-outlined',
  //   icon: 'receipt_long',
  //   class: '',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   role: ['Nurse'],
  //   submenu: [],
  // },
  // {
  //   path: '/nurse/records',
  //   title: 'MENUITEMS.PATIENT.MEDICAL-RECORD',
  //   iconType: 'material-icons-outlined',
  //   icon: 'restore_page',
  //   class: '',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   role: ['Nurse'],
  //   submenu: [],
  // },

];
